apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
secrets:
  - name: registry-credentials
  - name: tap-registry
  - name: git-secret
imagePullSecrets:
  - name: registry-credentials
  - name: tap-registry
